language: node_js
node_js:
 - 10

before_deploy:
  - ./build.sh
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "f1T4cW+k9FpAzZscM55n4aCvOUz0IWxncjcB147eZ4oNK1MqmBzoDBfUbZHaAikfdOi5xXGDO4bJFlfcM1knbm9QzyP7qZ01KM4P2Dh44R+tfpkjReJpGr0bOPFeT0NpjJNwkeIJhwrEBpxR6OfcA60QnuNcfLLJ4SjKG3PvE4H0lCMvXcJ4zmMDzbcFbcXFj2eyTarIgn8gl1WRaZmm7nnmftS3kyp6DdOB6vUXefcapUiGPuse/ZebbYb+acoN1cyVBEqQiwvYs9n6MdI0mBjzXtUWa08et16MKQwawX1AzoHnghZ9rCPO1TeIu8q8dxj9zb0/OLK8jUlY0D+Q95npn4RnOWV2rnAtSDNBFcQVU+/0dC1L9ECJgcbrrrOq1el64sDwTqvi3p2rx1GjSgP/+PWzfMisk9forZeOCrGwRF8d/jqI+wc+z/Gxo3J0IGSTycf4s/JSusTxQQOfZgiSw8Nm3FMOVBGCumJDlUA1re8aqxUhNYHyKMfSNMDF0gV57FuZ9ZDe8jIFlLT8I2JEqZrq/Rv8LHFEuWhfUBWpuFKfNh1sJBwy7PjMbumr1GtqnRnr8UEUT1ZTmrpdTN0C52HWbpn79Zci/sYAMzHXu7lFcfE6TGL9n9q1DAql3OQeDC4wlexXWsxWwVFeLEAR+jeQ9IZjOQOCDMtBunQ="
  secret_access_key:
    secure: "JA6GQv3z3XNX5/Hyp1rCFtuHkKpW8wfbY4Be66kRUvb7WfLmke/0QcP84kjW3jx1sYpJmyW+AyEmDMauFh1OxJF/3+CcNZPfHMmeQ2pwJLfhqt9Fyft0actTe6I0aVsaiAVeAS4zKfhXHYwFjUPMQkTKiNaJBi9arodQREWrjLq6ht4QRwjn/C5te5IUGS5B+alSMkWxqMU8ZVQ2BnublKd6CiwVW2qqyGAd9+41T0RX7+DkE6dorR52F8b/ILUQCDB0Rx1qi5kB25I26H/GnmnZue3qrI5VGi4uvvzchvrHZTiAp4gv04IU+lOImPD7OL2hbE1E5htMEqYQlxccoonpSxGeAba7hKg0EAujd7k1UVK+krPyrpn/sASMLBX6VUvACPldGWBHW0AVE4oq4COqAbNELWVPkStWjVdJqIXec+wziAJg7xJaus3fXn9gArrWrgUo6poJ2JUMtcQCa59R8b5ruHx+yqDzrL0a/i0xzuDtD1g0fPGfnzIZrjHM6vd6O6sCw8XRSZbiuS4hPg0FeylTXEuI+7J5W/0M9tuaM11FQxyHazkZZ1sqlfVU9pq4tuNZXpCEwXQI3ucgJT2911Shy5GfgEbm5wHwCYgfiay3mYW4QWd8HKhgWP3kd5u7tkf72hYOViCH21taHu28pCQh9jhQ3QKx7I2AxHE="
  region: "eu-west-1"
  app: "drone-station-webapp"
  env: "drone-station-dev"
  bucket_name: "drone-station-webapp-bucket"
  zip_file: "app.zip"
  skip_cleanup: true
  only_create_app_version: false
  on:
   branch: master
after_deploy:
 - rm app.zip
