language: node_js
node_js:
 - 10

script: echo "npm test temporarily disabled"
before_deploy:
  - ./build.sh
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "eu-west-1"
  app: "drone-station-webapp"
  env: "drone-station-dev"
  bucket_name: "drone-station-webapp-bucket"
  zip_file: "app.zip"
  skip_cleanup: true
  only_create_app_version: false
  on:
   branch: master
after_deploy:
 - rm app.zip
